//  Copyright 2010 Beth Randall

/*********************************
This file is part of CorpusSearch.

CorpusSearch is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

CorpusSearch is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with CorpusSearch.  If not, see <http://www.gnu.org/licenses/>.
************************************/


/*
  unsorted list of LexEntry objects generated by one sentence.
 */
package label_lexicon;

import java.util.*;
import syntree.*;
import basicinfo.*;

public class SentenceList {

    private Vector list;

    public SentenceList() {
	list = new Vector(); }

    public SentenceList(LexEntry lax) {
	 list = new Vector(); 
         list.addElement(lax);}

    public void addLexEntry(LexEntry lax) {
	list.addElement(lax); }

    public void addLexEntry(String label) {
	LexEntry lax = new LexEntry(label);
	list.addElement(lax); }

    public LexEntry entryAt(int i) {
	return ((LexEntry)list.elementAt(i)); }

    public boolean isEmpty() {
	return (list.isEmpty()); }

    public int size() {
	return(list.size()); }

    public void PrintToSystemErr() {
	LexEntry lax;
	System.err.println("SentenceList:  ");
	for (int i = 0; i < list.size(); i++) {
	    lax = entryAt(i);
	    lax.PrintToSystemErr(); } }
} 
