/* Generated By:JavaCC: Do not edit this line. ParseQueryConstants.java */
package CSParse;

public interface ParseQueryConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 8;
  int OPEN_PAREN = 9;
  int CLOSE_PAREN = 10;
  int CCOMMANDS = 11;
  int ISROOT = 12;
  int EXISTS = 13;
  int IPRES = 14;
  int HASSISTER = 15;
  int HASLABEL = 16;
  int PRES = 17;
  int IDOMS = 18;
  int IDOMSMOD = 19;
  int IDOMSLAST = 20;
  int IDOMSFIRST = 21;
  int IDOMSONLY = 22;
  int IDOMSVIATRACE = 23;
  int DOMST = 24;
  int DOMS = 25;
  int SAMEINDEX = 26;
  int IDOMSNUMBER = 27;
  int NEIGHBORHOOD = 28;
  int COLUMN = 29;
  int IDOMSTOTALSTUFF = 30;
  int DOMSWORDSSTUFF = 31;
  int INID = 32;
  int AND = 33;
  int OR = 34;
  int NOT = 35;
  int NOT_ARG = 36;
  int PREFIX = 37;
  int CURLY_LIST = 38;
  int INTARG = 39;
  int ARG = 40;
  int UNKNOWN = 41;

  int DEFAULT = 0;
  int WithinComment = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "<SINGLE_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "<CCOMMANDS>",
    "<ISROOT>",
    "<EXISTS>",
    "<IPRES>",
    "<HASSISTER>",
    "<HASLABEL>",
    "<PRES>",
    "<IDOMS>",
    "<IDOMSMOD>",
    "<IDOMSLAST>",
    "<IDOMSFIRST>",
    "<IDOMSONLY>",
    "<IDOMSVIATRACE>",
    "<DOMST>",
    "<DOMS>",
    "<SAMEINDEX>",
    "<IDOMSNUMBER>",
    "\"neighborhood\"",
    "<COLUMN>",
    "<IDOMSTOTALSTUFF>",
    "<DOMSWORDSSTUFF>",
    "<INID>",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"!\"",
    "<PREFIX>",
    "<CURLY_LIST>",
    "<INTARG>",
    "<ARG>",
    "<UNKNOWN>",
  };

}
