/* Generated By:JavaCC: Do not edit this line. ParseFramesConstants.java */
package FramesParse;

public interface ParseFramesConstants {

  int EOF = 0;
  int OPEN_PAREN = 7;
  int CLOSE_PAREN = 8;
  int OVER = 9;
  int ARG = 10;
  int LETTER = 11;
  int DIGIT = 12;
  int WCARD = 13;
  int DASH = 14;
  int PIPE = 15;
  int BSLASH = 16;
  int NUM = 17;
  int EQ = 18;
  int SQUOTE = 19;
  int PLUS = 20;
  int TILDE = 21;
  int UNKNOWN = 22;

  int DEFAULT = 0;
  int WithinComment = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "\"*/\"",
    "\"(\"",
    "\")\"",
    "<OVER>",
    "<ARG>",
    "<LETTER>",
    "<DIGIT>",
    "<WCARD>",
    "<DASH>",
    "<PIPE>",
    "<BSLASH>",
    "<NUM>",
    "<EQ>",
    "<SQUOTE>",
    "<PLUS>",
    "<TILDE>",
    "<UNKNOWN>",
  };

}
