//  Copyright 2010 Beth Randall

/*********************************
This file is part of CorpusSearch.

CorpusSearch is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

CorpusSearch is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with CorpusSearch.  If not, see <http://www.gnu.org/licenses/>.
************************************/

/*
  list of POSPairs generated by one file.
  Sorted into buckets by initial letter of text string.
 */
package lexicon;

import java.util.*;
import syntree.*;
import basicinfo.*;

public class FileList {

    private Vector list;
    private POSPairBucket A_bucket, B_bucket, C_bucket, D_bucket;
    private POSPairBucket E_bucket, F_bucket, G_bucket, H_bucket;
    private POSPairBucket I_bucket, J_bucket, K_bucket, L_bucket;
    private POSPairBucket M_bucket, N_bucket, O_bucket, P_bucket;
    private POSPairBucket Q_bucket, R_bucket, S_bucket, T_bucket;
    private POSPairBucket U_bucket, V_bucket, W_bucket, X_bucket;
    private POSPairBucket Y_bucket, Z_bucket, other_bucket;

    public FileList() {
	list = new Vector();
	other_bucket = new POSPairBucket(); list.addElement(other_bucket);
	A_bucket = new POSPairBucket(); list.addElement(A_bucket);
	B_bucket = new POSPairBucket(); list.addElement(B_bucket);
	C_bucket = new POSPairBucket(); list.addElement(C_bucket);
	D_bucket = new POSPairBucket(); list.addElement(D_bucket);
	E_bucket = new POSPairBucket(); list.addElement(E_bucket);
	F_bucket = new POSPairBucket(); list.addElement(F_bucket);
	G_bucket = new POSPairBucket(); list.addElement(G_bucket);
	H_bucket = new POSPairBucket(); list.addElement(H_bucket);
	I_bucket = new POSPairBucket(); list.addElement(I_bucket);
	J_bucket = new POSPairBucket(); list.addElement(J_bucket);
	K_bucket = new POSPairBucket(); list.addElement(K_bucket);
	L_bucket = new POSPairBucket(); list.addElement(L_bucket);
	M_bucket = new POSPairBucket(); list.addElement(M_bucket);
	N_bucket = new POSPairBucket(); list.addElement(N_bucket);
	O_bucket = new POSPairBucket(); list.addElement(O_bucket);
	P_bucket = new POSPairBucket(); list.addElement(P_bucket);
	Q_bucket = new POSPairBucket(); list.addElement(Q_bucket);
	R_bucket = new POSPairBucket(); list.addElement(R_bucket);
	S_bucket = new POSPairBucket(); list.addElement(S_bucket);
	T_bucket = new POSPairBucket(); list.addElement(T_bucket);
	U_bucket = new POSPairBucket(); list.addElement(U_bucket);
	V_bucket = new POSPairBucket(); list.addElement(V_bucket);
	W_bucket = new POSPairBucket(); list.addElement(W_bucket);
	X_bucket = new POSPairBucket(); list.addElement(X_bucket);
	Y_bucket = new POSPairBucket(); list.addElement(Y_bucket);
	Z_bucket = new POSPairBucket(); list.addElement(Z_bucket); }

    public int size() {
	return list.size(); }

    public boolean isEmpty() {
	POSPairBucket paris;
	for (int i = 0; i < list.size(); i++) {
	    paris = (POSPairBucket)list.elementAt(i);
	    if (!paris.isEmpty()) {
		return false; } }
	return true; }

    public POSPairBucket bucketAt(int i) {
	return(POSPairBucket)list.elementAt(i); }

    public void addSentenceList(SentenceList sent) {
	for (int i = 0; i < sent.size(); i++) {
	    this.addPOSPair(sent.POSPairAt(i)); } }
					  
    public void addPOSPair(POSPair paris) {
	int dex;
	POSPairBucket bucket;
	dex = paris.getASCIInum();
	bucket = (POSPairBucket)list.elementAt(dex);
	bucket.AddPOSPair(paris);
	return; }

    public void PrintToSystemErr() {
	POSPairBucket bucket;
	LexEntry enter;
	System.err.println("FileList:  ");
	for (int i = 0; i < list.size(); i++) {
	    System.err.println("bucket:  ") ;
	    bucket = (POSPairBucket)list.elementAt(i);
	    bucket.PrintToSystemErr(); } }

} 
