//  Copyright 2010 Beth Randall

/*********************************
This file is part of CorpusSearch.

CorpusSearch is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

CorpusSearch is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with CorpusSearch.  If not, see <http://www.gnu.org/licenses/>.
************************************/

/*
  SentenceFrame is a list of SingleFrame objects -- all the SingleFrame
  objects generated by the search of one sentence.
 */
package frames;

import java.util.*;

public class SentenceFrame extends ListFrames {

    private Vector frames_per_sentence;

    public SentenceFrame() {
	frames_per_sentence = new Vector(); }

    public SentenceFrame(SingleFrame framed) {
	frames_per_sentence = new Vector();
	this.addSingleFrame(framed); }

    public void addSingleFrame(SingleFrame framed) {
	frames_per_sentence.addElement(framed); }

    public int size() {
	return (frames_per_sentence.size()); }

    public boolean isEmpty() {
	return (frames_per_sentence.isEmpty()); }

    public SingleFrame getSingleFrame(int i) {
	return ((SingleFrame)frames_per_sentence.elementAt(i)); }

    public void PrintToSystemErr() {
	SingleFrame framed;

	System.err.println("frames_per_sentence:  ");
	for (int i = 0; i < this.size(); i++) {
	    framed = this.getSingleFrame(i);
	    System.err.print(i + ".)  ");
	    framed.PrintToSystemErr(); }
	System.err.println("");
    }

}
