/* Generated By:JavaCC: Do not edit this line. ParseCodingQueryConstants.java */
package CodingParse;

public interface ParseCodingQueryConstants {

  int EOF = 0;
  int OPEN_CURLY = 7;
  int CLOSE_CURLY = 8;
  int COL_NUM = 9;
  int COL_LABEL = 10;
  int ELSE = 11;
  int OPEN_PAREN = 12;
  int CLOSE_PAREN = 13;
  int ISROOT = 14;
  int EXISTS = 15;
  int IPRES = 16;
  int HASSISTER = 17;
  int HASLABEL = 18;
  int PRES = 19;
  int IDOMS = 20;
  int IDOMSMOD = 21;
  int IDOMSLAST = 22;
  int IDOMSFIRST = 23;
  int IDOMSONLY = 24;
  int IDOMSVIATRACE = 25;
  int DOMST = 26;
  int DOMS = 27;
  int CCOMMANDS = 28;
  int SAMEINDEX = 29;
  int IDOMSNUMBER = 30;
  int COLUMN = 31;
  int IDOMSTOTALSTUFF = 32;
  int DOMSWORDSSTUFF = 33;
  int INID = 34;
  int AND = 35;
  int OR = 36;
  int NOT = 37;
  int NOT_ARG = 38;
  int PREFIX = 39;
  int INTARG = 40;
  int ARG = 41;
  int UNKNOWN = 42;

  int DEFAULT = 0;
  int WithinComment = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "\"*/\"",
    "\"{\"",
    "\"}\"",
    "<COL_NUM>",
    "<COL_LABEL>",
    "\"ELSE\"",
    "\"(\"",
    "\")\"",
    "<ISROOT>",
    "<EXISTS>",
    "<IPRES>",
    "<HASSISTER>",
    "<HASLABEL>",
    "<PRES>",
    "<IDOMS>",
    "<IDOMSMOD>",
    "<IDOMSLAST>",
    "<IDOMSFIRST>",
    "<IDOMSONLY>",
    "<IDOMSVIATRACE>",
    "<DOMST>",
    "<DOMS>",
    "<CCOMMANDS>",
    "<SAMEINDEX>",
    "<IDOMSNUMBER>",
    "<COLUMN>",
    "<IDOMSTOTALSTUFF>",
    "<DOMSWORDSSTUFF>",
    "<INID>",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"!\"",
    "<PREFIX>",
    "<INTARG>",
    "<ARG>",
    "<UNKNOWN>",
  };

}
